[project]
name = "call-me-maybe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "hamza-el-kamel", email = "hamzaelkamel4@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "llm-sdk",
    "numpy>=2.2.6",
    "pydantic>=2.13.4",
]

[project.scripts]
call-me-maybe = "call_me_maybe:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "llm_sdk",
]

[tool.uv.sources]
llm-sdk = { workspace = true }

[tool.mypy]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "llm_sdk"
ignore_missing_imports = true
follow_imports = "skip"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-timeout>=2.4.0",
]
